CRIME_CATALOG = [
    {"law_name": "Indian Penal Code", "ipc_section": "121", "category": "State Security", "severity": "HIGH", "description": "Waging war against the State"},
    {"law_name": "Indian Penal Code", "ipc_section": "141", "category": "Public Order", "severity": "MEDIUM", "description": "Unlawful assembly"},
    {"law_name": "Indian Penal Code", "ipc_section": "144", "category": "Public Order", "severity": "MEDIUM", "description": "Joining unlawful assembly with deadly weapon restriction context"},
    {"law_name": "Indian Penal Code", "ipc_section": "146", "category": "Public Order", "severity": "MEDIUM", "description": "Rioting"},
    {"law_name": "Indian Penal Code", "ipc_section": "147", "category": "Public Order", "severity": "MEDIUM", "description": "Rioting / unlawful assembly"},
    {"law_name": "Indian Penal Code", "ipc_section": "148", "category": "Public Order", "severity": "HIGH", "description": "Rioting with deadly weapon"},
    {"law_name": "Indian Penal Code", "ipc_section": "151", "category": "Public Order", "severity": "MEDIUM", "description": "Knowingly joining unlawful assembly"},
    {"law_name": "Indian Penal Code", "ipc_section": "153-A", "category": "Public Order", "severity": "HIGH", "description": "Promoting enmity"},
    {"law_name": "Indian Penal Code", "ipc_section": "295-A", "category": "Public Order", "severity": "HIGH", "description": "Religious insult / deliberate outrage"},
    {"law_name": "Indian Penal Code", "ipc_section": "268", "category": "Public Nuisance", "severity": "LOW", "description": "Public nuisance"},
    {"law_name": "Indian Penal Code", "ipc_section": "302", "category": "Violent", "severity": "HIGH", "description": "Murder"},
    {"law_name": "Indian Penal Code", "ipc_section": "304-B", "category": "Women Safety", "severity": "HIGH", "description": "Dowry death"},
    {"law_name": "Indian Penal Code", "ipc_section": "307", "category": "Violent", "severity": "HIGH", "description": "Attempt to murder"},
    {"law_name": "Indian Penal Code", "ipc_section": "322", "category": "Violent", "severity": "MEDIUM", "description": "Voluntarily causing grievous hurt"},
    {"law_name": "Indian Penal Code", "ipc_section": "324", "category": "Violent", "severity": "MEDIUM", "description": "Hurt by dangerous weapon"},
    {"law_name": "Indian Penal Code", "ipc_section": "351", "category": "Violent", "severity": "LOW", "description": "Assault"},
    {"law_name": "Indian Penal Code", "ipc_section": "354", "category": "Women Safety", "severity": "HIGH", "description": "Assault on woman"},
    {"law_name": "Indian Penal Code", "ipc_section": "509", "category": "Women Safety", "severity": "MEDIUM", "description": "Insulting modesty of a woman"},
    {"law_name": "Indian Penal Code", "ipc_section": "498-A", "category": "Women Safety", "severity": "MEDIUM", "description": "Cruelty by husband or relatives"},
    {"law_name": "Indian Penal Code", "ipc_section": "363", "category": "Kidnapping", "severity": "HIGH", "description": "Kidnapping"},
    {"law_name": "Indian Penal Code", "ipc_section": "364", "category": "Kidnapping", "severity": "HIGH", "description": "Kidnapping or abducting with intent to murder"},
    {"law_name": "Indian Penal Code", "ipc_section": "365", "category": "Kidnapping", "severity": "HIGH", "description": "Kidnapping or abducting with intent to confine"},
    {"law_name": "Indian Penal Code", "ipc_section": "366", "category": "Kidnapping", "severity": "HIGH", "description": "Kidnapping woman / compel marriage"},
    {"law_name": "Indian Penal Code", "ipc_section": "376", "category": "Women Safety", "severity": "HIGH", "description": "Rape"},
    {"law_name": "Indian Penal Code", "ipc_section": "379", "category": "Property", "severity": "MEDIUM", "description": "Theft"},
    {"law_name": "Indian Penal Code", "ipc_section": "380", "category": "Property", "severity": "MEDIUM", "description": "Theft in dwelling"},
    {"law_name": "Indian Penal Code", "ipc_section": "383", "category": "Property", "severity": "MEDIUM", "description": "Extortion"},
    {"law_name": "Indian Penal Code", "ipc_section": "390", "category": "Property", "severity": "HIGH", "description": "Robbery definition"},
    {"law_name": "Indian Penal Code", "ipc_section": "391", "category": "Property", "severity": "HIGH", "description": "Dacoity definition"},
    {"law_name": "Indian Penal Code", "ipc_section": "392", "category": "Property", "severity": "HIGH", "description": "Robbery"},
    {"law_name": "Indian Penal Code", "ipc_section": "395", "category": "Property", "severity": "HIGH", "description": "Dacoity"},
    {"law_name": "Indian Penal Code", "ipc_section": "396", "category": "Property", "severity": "HIGH", "description": "Dacoity with murder"},
    {"law_name": "Indian Penal Code", "ipc_section": "397", "category": "Property", "severity": "HIGH", "description": "Robbery with attempt to cause death"},
    {"law_name": "Indian Penal Code", "ipc_section": "411", "category": "Property", "severity": "MEDIUM", "description": "Receiving stolen property"},
    {"law_name": "Indian Penal Code", "ipc_section": "420", "category": "Fraud", "severity": "MEDIUM", "description": "Cheating and dishonestly inducing delivery"},
    {"law_name": "Indian Penal Code", "ipc_section": "441", "category": "Burglary", "severity": "LOW", "description": "Criminal trespass"},
    {"law_name": "Indian Penal Code", "ipc_section": "442", "category": "Burglary", "severity": "MEDIUM", "description": "House trespass"},
    {"law_name": "Indian Penal Code", "ipc_section": "447", "category": "Burglary", "severity": "LOW", "description": "Punishment for criminal trespass"},
    {"law_name": "Indian Penal Code", "ipc_section": "448", "category": "Burglary", "severity": "MEDIUM", "description": "House trespass"},
    {"law_name": "Indian Penal Code", "ipc_section": "454", "category": "Burglary", "severity": "HIGH", "description": "Lurking house trespass / house breaking"},
    {"law_name": "Indian Penal Code", "ipc_section": "457", "category": "Burglary", "severity": "HIGH", "description": "Night house breaking"},
    {"law_name": "Indian Penal Code", "ipc_section": "465", "category": "Fraud", "severity": "MEDIUM", "description": "Forgery"},
    {"law_name": "Indian Penal Code", "ipc_section": "467", "category": "Fraud", "severity": "HIGH", "description": "Forgery of valuable security"},
    {"law_name": "Indian Penal Code", "ipc_section": "468", "category": "Fraud", "severity": "HIGH", "description": "Forgery for purpose of cheating"},
    {"law_name": "Indian Penal Code", "ipc_section": "470", "category": "Fraud", "severity": "MEDIUM", "description": "Forged document"},
    {"law_name": "Indian Penal Code", "ipc_section": "471", "category": "Fraud", "severity": "MEDIUM", "description": "Using forged document"},
    {"law_name": "Indian Penal Code", "ipc_section": "489-A", "category": "Fraud", "severity": "HIGH", "description": "Counterfeiting currency"},
    {"law_name": "Indian Penal Code", "ipc_section": "504", "category": "Public Order", "severity": "LOW", "description": "Intentional insult"},
    {"law_name": "Indian Penal Code", "ipc_section": "506", "category": "Public Order", "severity": "MEDIUM", "description": "Criminal intimidation"},
    {"law_name": "NDPS Act", "ipc_section": "20", "category": "NDPS", "severity": "HIGH", "description": "Cannabis / production / possession"},
    {"law_name": "NDPS Act", "ipc_section": "21", "category": "NDPS", "severity": "HIGH", "description": "Manufactured drugs / possession"},
    {"law_name": "NDPS Act", "ipc_section": "22", "category": "NDPS", "severity": "HIGH", "description": "Psychotropic substances"},
    {"law_name": "Gambling Act", "ipc_section": "13", "category": "Gambling", "severity": "LOW", "description": "Gambling offence"},
    {"law_name": "Arms Act", "ipc_section": "25", "category": "Arms Act", "severity": "HIGH", "description": "Illegal arms possession / use"},
    {"law_name": "Excise Act", "ipc_section": "60", "category": "Excise Act", "severity": "MEDIUM", "description": "Excise violation"},
    {"law_name": "Excise Act", "ipc_section": "60(2)", "category": "Excise Act", "severity": "HIGH", "description": "Aggravated excise violation"},
    {"law_name": "Excise Act", "ipc_section": "72", "category": "Excise Act", "severity": "HIGH", "description": "Serious excise violation"},
    {"law_name": "Cow Protection Act", "ipc_section": "3", "category": "Cow Protection", "severity": "MEDIUM", "description": "Cow protection violation"},
    {"law_name": "Cow Protection Act", "ipc_section": "5", "category": "Cow Protection", "severity": "MEDIUM", "description": "Transport / slaughter linked violation"},
    {"law_name": "Cow Protection Act", "ipc_section": "11", "category": "Cow Protection", "severity": "MEDIUM", "description": "Cow protection offence"},
    {"law_name": "SC/ST Act", "ipc_section": "3", "category": "SC/ST Act", "severity": "HIGH", "description": "Atrocity / discrimination offence"},
    {"law_name": "Mineral and Mining Act", "ipc_section": "4", "category": "Mining Act", "severity": "MEDIUM", "description": "Illegal mining operation"},
    {"law_name": "Mineral and Mining Act", "ipc_section": "21", "category": "Mining Act", "severity": "HIGH", "description": "Penalty for illegal mining"},
    {"law_name": "Immoral Traffic Prevention Act", "ipc_section": "3", "category": "ITPA", "severity": "HIGH", "description": "Brothel keeping / trafficking-linked offence"},
    {"law_name": "Immoral Traffic Prevention Act", "ipc_section": "4", "category": "ITPA", "severity": "HIGH", "description": "Living on earnings of prostitution"},
    {"law_name": "Immoral Traffic Prevention Act", "ipc_section": "5", "category": "ITPA", "severity": "HIGH", "description": "Procuring / inducing for prostitution"},
    {"law_name": "Goonda Act", "ipc_section": "3", "category": "Goonda Act", "severity": "HIGH", "description": "Habitual offender preventive detention context"},
    {"law_name": "IRAD / Accident", "ipc_section": "IRAD-ACCIDENT", "category": "Accident", "severity": "HIGH", "description": "Accident-prone incident cluster"},
]


def catalog_by_category():
    grouped = {}
    for row in CRIME_CATALOG:
        grouped.setdefault(row["category"], []).append(row)
    return grouped
